#Create a ruby file and print seven lines with print and puts
puts "hi"
puts "I'm Ser"
puts "I'm working"
puts "with ruby"
puts "well, I'm trying"
puts ":S"
puts "----------------"
print "and on the "
print "way, I "
print "practice "
print "also English "
print "because "
print "I need"
print "---------------"

